import { Inter } from "next/font/google";
import "../styles/globals.css";

import type { Metadata } from "next";
import Image from "next/image";
import { useRouter, redirect } from 'next/navigation'
import Link from "next/link";
import { SessionProvider, useSession } from "next-auth/react";
import initialScripts from "@/lib/initial-scripts";
import { auth } from "@/auth";
import NavBar from "@/components/NavBar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  await initialScripts();

  const session: any = await auth();
  // console.log("session".bgCyan, session);

  return (
    <html lang="en">
      <head>
        <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200" />
      </head>
      <body className="">
        <div className="bg-violet-200 h-screen">
          {session?.user ? <NavBar /> : <></>}
          <SessionProvider session={session}>
            {children}
          </SessionProvider>
        </div>
      </body>
    </html>
  );
}
