import { Inter, K2D } from "next/font/google";
import "../styles/globals.css";

import type { Metadata } from "next";
import Image from "next/image";
import { useRouter, redirect, usePathname } from 'next/navigation'
import Link from "next/link";
import { SessionProvider, useSession } from "next-auth/react";
import initialScripts from "@/lib/initial-scripts";
import { auth } from "@/auth";
import NavBar from "@/components/UI/NavBar";
import CheckSession from "@/components/CheckSessionClient";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const font = K2D({
  subsets: ["latin"],
  weight: "200",
});

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  await initialScripts();

  const session: any = await auth();
  // console.log("session".bgCyan, session);

  // const route = useRouter();
  // console.log(route);
  // const firstPortion = route.split('/')[0];
  // console.log(firstPortion);
  
  return (
    <html lang="en">
      <head>
        <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200" />
      </head>
      <body>
        <div className={`${font.className} h-svh overflow-hidden`}>
          <SessionProvider session={session}>
            <CheckSession>
              <NavBar />
              {children}
            </CheckSession>
          </SessionProvider>
        </div>
      </body>
    </html>
  );
}
